# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/3i-a1-2022-062/workspace/yolo11_track/rnd.ml.object-detection/detection/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/lib/cmake/ncnn/ncnn-release.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/lib/cmake/ncnn/ncnn.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/lib/cmake/ncnn/ncnnConfig.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/lib/cmake/opencv4/OpenCVConfig-version.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/lib/cmake/opencv4/OpenCVConfig.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/lib/cmake/opencv4/OpenCVModules-release.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/lib/cmake/opencv4/OpenCVModules.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/CMakeParseImplicitLinkInfo.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/CheckCSourceCompiles.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/CheckIncludeFile.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/CheckLibraryExists.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/FindOpenMP.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/FindPackageHandleStandardArgs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/FindPackageMessage.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/FindThreads.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/Internal/CheckSourceCompiles.cmake))

/Users/3i-a1-2022-062/workspace/yolo11_track/rnd.ml.object-detection/demo/linux/build_test/CMakeFiles/cmake.check_cache: $(TARGETS)
	/opt/homebrew/bin/cmake -S/Users/3i-a1-2022-062/workspace/yolo11_track/rnd.ml.object-detection/demo/linux -B/Users/3i-a1-2022-062/workspace/yolo11_track/rnd.ml.object-detection/demo/linux/build_test
